# Generated by Django 5.2.5 on 2025-09-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unidad',
        ),
    ]
