# Generated by Django 5.2.5 on 2025-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_material_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('m', 'Metro'), ('cm', 'Centímetro'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unidad'),
        ),
    ]
